$servip = 172.16.16.1/24
$subnet = 172.16.16.0/24
$endpoint = example.org:30000
$tincport = 30000
$httport = 0.0.0.0:30001
$tincnet = esa
$tincdir = C:/UserDocument/tinc/esa
$servname = esa_server
$servpub = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
